### ISSUE TITLE
Log to file causes program to hang

### ISSUE THREAD

**Issue by HannahBrown** [karakun/OpenWebStart#220]
The first time that a program is run with log to file enabled, there is no error. However, if it is run a second time, the program hangs when trying to open the log file. This only happens on Windows.

No log files are created. If log to console is enabled, the program stops right before printing
> net.sourceforge.jnlp.util.logging.FileLog: Attempting to log into: {path}

**Comment by AndreasEhret** [comment]
Could you give us a little more details on your logging settings, did you checked all three check boxes in the settings?
Which OWS version you are talking about, 1.1.6? Windows 10? Please share the full logs with us not only the last log entry.

**Comment by HannahBrown** [comment]
This is on Windows 10 and OWS 1.1.6 (however, I'm not sure if this is the first version with the error, as I skipped from 1.1.1 to 1.1.6). 

I have attached two files: one where both log to file and log to standard out are enabled (the log messages are copied from the console), and one where only log to standard out is enabled. In both cases, 'Activate debug logging' is unchecked, though debug messages are still included.

When log to file is enabled, the program just stops. There are no further log messages displayed on the console, and the splash screen remains up. However, the program does not open.

[log-to-file-hang.txt](https://github.com/karakun/OpenWebStart/files/4370800/log-to-file-hang.txt)
[log-to-console-only.txt](https://github.com/karakun/OpenWebStart/files/4370801/log-to-console-only.txt)

**Comment by sclassen** [comment]
can't find any significant difference in the logs.
To which directory are you writing the logs?

**Comment by HannahBrown** [comment]
I am leaving it as the default for the single-user install, which is C:/Users/Hannah/.config/icedtea-web/log.

**Comment by AndreasEhret** [comment]
could you share the deployment.properties and the .jnlp with us? 
You find the properties in <user home>/.config/icedtea-web
Did you also tried a for all users install? Does it make any difference?

**Comment by HannahBrown** [comment]
I did try multi-user install, and the same thing happened. I could not find any differences in the behavior or the logs.

Both deployment.properties and a redacted version of the jnlp are in the attached zip file.

[application.zip](https://github.com/karakun/OpenWebStart/files/4387830/application.zip)

**Comment by AndreasEhret** [comment]
did you edited your deployment.properties manually at some point in time? What is irritating me is the empty 'deployment.proxy.http.host=' while missing 'deployment.proxy.type=1' at the same time. Can you check your proxy settings, either with the OWS settings UI (when you set the proxy settings it should update the deployment properties or removing 'deployment.proxy.http.host=' manually. Let's see if it changes anything.

**Comment by HannahBrown** [comment]
At one point, I had edited it, but I thought I had removed all of my edits. Regardless, making the change you suggested (through the settings UI) did not change the behavior: like before, it successfully started the program once, and then when I tried to start it a second time, it hanged when trying to open the log file.

Attached is my new deployment.properties file.
[application.zip](https://github.com/karakun/OpenWebStart/files/4388664/application.zip)

**Comment by sclassen** [comment]
We went through the config and the logs one more time.
The bad news is we cannot find anything that looks suspicious.
So our best guess right now is that it is related to the permissions on the file system.

What are the permissions that your user has on the following directories:
- C:\Users\Hannah
- C:\Users\Hannah\.config\icedtea-web\log

**Comment by HannahBrown** [comment]
C:\Users\Hannah - Full control for both Hannah and System
C:\Users\Hannah\.config\icedtea-web\log - Full control for both Hannah and System

**Comment by sclassen** [comment]
OK, that sounds like it should not be a problem
Do you see any files ending in `.temp` in the log directory?

**Comment by HannahBrown** [comment]
There are none.

**Comment by sclassen** [comment]
Darn, now I am out of ideas

**Comment by sclassen** [comment]
Can you try another computer to see if it is some windows configuration that is causing the troubles?
So far we have not seen this behavior on any other installation.

Is your current machine a corporate computer with restricted user rights or is your user a regular windows user with full access?

**Comment by HannahBrown** [comment]
I first discovered this issue on a coworker's Windows 10 computer, which is a corporate computer. However, I replicated it on my Windows 10 VM, where I have full access. The logs and data I have been sending you are from my VM. I did not see any difference, either in behavior or in console logs, between my VM and my coworker's computer, but I can send you their logs as well if you are interested.

I discovered that clearing the .cache folder allows the program to run with log to file enabled. However, like before, it only allows it to run once before it hangs again.

**Comment by sclassen** [comment]
I don't think that more log files would help. I need to think some more...

**Comment by AndreasEhret** [comment]
Can you please try with 1.1.7 once we released it (before Easter). We added some more log details and fixed an issue with logging to file.

**Comment by AndreasEhret** [comment]
1.1.7 is available, please restest.

**Comment by HannahBrown** [comment]
Unfortunately, 1.1.7 did not fix the issue. Moreover, the issue is worse - previously, I could completely empty the .cache folder and rerun the program, and it would work; that no longer works.

There appears to be a new error in the console logs shortly before it hangs, so I attached the new logs.
[1.1.7-hang.txt](https://github.com/karakun/OpenWebStart/files/4457205/1.1.7-hang.txt)

**Comment by sclassen** [comment]
Examining the new log shows still the same messages just in a different order.

Sorry I am out of ideas

**Comment by janakmulani** [comment]
Please try with OWS 1.20 which will be released next week. it has some changes regarding logging.

**Comment by Jamila891** [comment]
@HannahBrown 1.2.0 has been released.
