### ISSUE TITLE
ClassNotFoundException and NoClassDefFoundError

### ISSUE THREAD

**Issue by Pheil** [karakun/OpenWebStart#29]
There's probably a 5% chance this is an issue versus me just doing something that's not going to work.  I re-wrote my JNLP from 'applet-desc' to a standalone 'resources' Java application based on https://github.com/karakun/OpenWebStart/issues/26#issuecomment-528898314.  

```
Tue Sep 10 13:08:40 EDT 2019 [ERROR  ] net.sourceforge.jnlp.runtime.JNLPClassLoader:
ERROR
java.lang.ClassNotFoundException: netscape.javascript.JSException
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1715)
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1515)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:439)
        at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:782)

Tue Sep 10 13:08:40 EDT 2019 [ERROR  ] net.sourceforge.jnlp.Launcher:
ERROR
java.lang.NoClassDefFoundError: netscape/javascript/JSException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:439)
        at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:782)
Caused by: java.lang.ClassNotFoundException: netscape.javascript.JSException
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1557)
        ... 8 more

Exception in thread "Oracle Applications" java.lang.RuntimeException: java.lang.NoClassDefFoundError: netscape/javascript/JSException
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:805)
Caused by: java.lang.NoClassDefFoundError: netscape/javascript/JSException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:439)
        at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:782)
Caused by: java.lang.ClassNotFoundException: netscape.javascript.JSException
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1557)
        ... 8 more
```

**Comment by Pheil** [comment]
Sure.

[itw-clienta-2019-09-13_09_10_13.407.log](https://github.com/karakun/OpenWebStart/files/3610177/itw-clienta-2019-09-13_09_10_13.407.log)
[itw-javantx-2019-09-13_09_10_10.632.log](https://github.com/karakun/OpenWebStart/files/3610178/itw-javantx-2019-09-13_09_10_10.632.log)
[OWS_jnlp.zip](https://github.com/karakun/OpenWebStart/files/3610191/OWS_jnlp.zip)

**Comment by AndreasEhret** [comment]
``` 
Fri Sep 13 09:10:16 EDT 2019 [DEBUG  ] net.sourceforge.jnlp.cache.ResourceDownloader: For location=http://pafoap01:8888/forms/java/icons.jnlp state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING the server returned 404 code for GET request for http://pafoap01:8888/forms/java/icons.jnlp
Fri Sep 13 09:10:16 EDT 2019 [WARNING] net.sourceforge.jnlp.cache.ResourceDownloader: You are trying to get resource http://pafoap01:8888/forms/java/icons.jnlp but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure
Fri Sep 13 09:10:16 EDT 2019 [DEBUG  ] net.sourceforge.jnlp.runtime.JNLPProxySelector: Selecting proxy for: http://pafoap01:8888/forms/java/icons.jnlp
Fri Sep 13 09:10:16 EDT 2019 [ERROR  ] net.sourceforge.jnlp.runtime.JNLPClassLoader:
ERROR
java.io.IOException: java.lang.NullPointerException
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:375)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:286)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:269)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:320)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:547)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:582)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:341)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:425)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:499)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:472)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:662)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:412)
	at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:782)
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:372)
	... 13 more
```
it looks like this my be the cause of the error. The URL http://pafoap01:8888/forms/java/icons.jnlp returns a 404

**Comment by Pheil** [comment]
Whoops, that was a typo when I was testing if different file locations would work.  Since that file is signed with a different cert it gave me issues with Webstart.  When correcting that to a icons.jar it looks like most the errors are the same except maybe another "xmlparser.ParseException"

[itw-clienta-2019-09-16_09_06_46.151.log](https://github.com/karakun/OpenWebStart/files/3616454/itw-clienta-2019-09-16_09_06_46.151.log)

**Comment by sclassen** [comment]
@Pheil Can you please retest this issue with OWS 1.0 as we have fixed many issues with resource downloading and class loading

**Comment by Pheil** [comment]
I re-tried various configurations of the JNLP to try to see if I had my structure wrong, but I still cannot get the application to launch.   Maybe this debug line points to the real issue?  (This is with 1.8.0_222)

`[DEBUG  ] net.adoptopenjdk.icedteaweb.manifest.ManifestAttributesChecker: Entry-Point manifest attribute for yours 'oracle.forms.engine.Main' not found. Continuing.`

Using 11.0.5 I get this error

`net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:458)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: java.lang.NoSuchMethodException: oracle.forms.engine.Main.main([Ljava.lang.String;)
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:438)
	... 2 more
`

**Comment by sclassen** [comment]
What do you mean by 

> I re-wrote my JNLP from 'applet-desc' to a standalone 'resources' Java application based on #26 (comment).

Simply changing the 'applet-desc' into an 'application-desc' will not work. An application expects a `public static void main(String... args)` method to be present in the main class. The applet will expect a class extending `java.applet.Applet

**Comment by Pheil** [comment]
oh, sorry...  Then this is not a bug.  Thanks for the follow up.

**Comment by sclassen** [comment]
have you tried to run it with the newest OWS as an applet-desc? maybe you are lucky

**Comment by Pheil** [comment]
Yea, unfortunately I get the same errors.
